# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: false

cache:
  packages: true

warnings_are_errors: true

matrix:
  include:
    - name: "Spark 2.2.1 (R oldrel, oraclejdk8)"
      r: oldrel
      env:
        - SPARK_VERSION="2.2.1"
        - JAVA_VERSION=oraclejdk8
    - name: "Spark 2.3.2 (R release, oraclejdk8)"
      r: release
      env:
        - SPARK_VERSION="2.3.2"
        - JAVA_VERSION=oraclejdk8
    - name: "Spark 2.4.0 (R release, oraclejdk8)"
      r: release
      env:
        - SPARK_VERSION="2.4.0"
        - JAVA_VERSION=oraclejdk8
        - CODE_COVERAGE="true"